# Generated by Django 3.0.3 on 2020-05-15 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitfile', models.FileField(upload_to='activities/%Y/%m/%d')),
                ('activity_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('start_position_lat', models.IntegerField(blank=True, default=None, null=True)),
                ('start_position_long', models.IntegerField(blank=True, default=None, null=True)),
                ('total_elapsed_time', models.FloatField(blank=True, default=None, null=True)),
                ('total_timer_time', models.FloatField(blank=True, default=None, null=True)),
                ('total_distance', models.FloatField(blank=True, default=None, null=True)),
                ('total_cycles', models.IntegerField(blank=True, default=None, null=True)),
                ('total_work', models.IntegerField(blank=True, default=None, null=True)),
                ('enhanced_avg_speed', models.IntegerField(blank=True, default=None, null=True)),
                ('enhanced_max_speed', models.IntegerField(blank=True, default=None, null=True)),
                ('enhanced_avg_altitude', models.IntegerField(blank=True, default=None, null=True)),
                ('enhanced_min_altitude', models.IntegerField(blank=True, default=None, null=True)),
                ('enhanced_max_altitude', models.IntegerField(blank=True, default=None, null=True)),
                ('total_calories', models.IntegerField(blank=True, default=None, null=True)),
                ('avg_speed', models.IntegerField(blank=True, default=None, null=True)),
                ('max_speed', models.IntegerField(blank=True, default=None, null=True)),
                ('avg_power', models.IntegerField(blank=True, default=None, null=True)),
                ('max_power', models.IntegerField(blank=True, default=None, null=True)),
                ('total_ascent', models.IntegerField(blank=True, default=None, null=True)),
                ('total_descent', models.IntegerField(blank=True, default=None, null=True)),
                ('num_laps', models.IntegerField(blank=True, default=None, null=True)),
                ('normalized_power', models.IntegerField(blank=True, default=None, null=True)),
                ('training_stress_score', models.FloatField(blank=True, default=None, null=True)),
                ('intensity_factor', models.FloatField(blank=True, default=None, null=True)),
                ('threshold_power', models.IntegerField(blank=True, default=None, null=True)),
                ('event', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('event_type', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('sport', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('sub_sport', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('avg_heart_rate', models.IntegerField(blank=True, default=None, null=True)),
                ('max_heart_rate', models.IntegerField(blank=True, default=None, null=True)),
                ('avg_cadence', models.IntegerField(blank=True, default=None, null=True)),
                ('max_cadence', models.IntegerField(blank=True, default=None, null=True)),
                ('total_training_effect', models.FloatField(blank=True, default=None, null=True)),
                ('avg_temperature', models.IntegerField(blank=True, default=None, null=True)),
                ('max_temperature', models.IntegerField(blank=True, default=None, null=True)),
                ('avg_fractional_cadence', models.FloatField(blank=True, default=None, null=True)),
                ('max_fractional_cadence', models.FloatField(blank=True, default=None, null=True)),
                ('total_fractional_cycles', models.FloatField(blank=True, default=None, null=True)),
                ('total_anaerobic_training_effect', models.FloatField(blank=True, default=None, null=True)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=30)),
                ('garmin_product', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('position_lat', models.IntegerField(blank=True, default=None, null=True)),
                ('position_long', models.IntegerField(blank=True, default=None, null=True)),
                ('distance', models.FloatField(blank=True, default=None, null=True)),
                ('accumulated_power', models.IntegerField(blank=True, default=None, null=True)),
                ('speed', models.FloatField(blank=True, default=None, null=True)),
                ('altitude', models.FloatField(blank=True, default=None, null=True)),
                ('power', models.IntegerField(blank=True, default=None, null=True)),
                ('heart_rate', models.IntegerField(blank=True, default=None, null=True)),
                ('cadence', models.IntegerField(blank=True, default=None, null=True)),
                ('temperature', models.IntegerField(blank=True, default=None, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Activity')),
            ],
        ),
    ]
