# Generated by Django 3.0.3 on 2020-05-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='url',
        ),
    ]
