# Generated by Django 3.0.3 on 2020-06-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0006_auto_20200516_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('activity', models.ManyToManyField(to='compare.Activity')),
            ],
        ),
    ]
