# Generated by Django 3.0.3 on 2020-06-07 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0007_activitygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitygroup',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitygroup',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
